name: Build Mihomo Package

on:
  workflow_dispatch:
  # schedule:
  #   - cron: "0 4 * * *"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout mi branch
        uses: actions/checkout@v4
        with:
          ref: mi

      - name: Install tools
        run: |
          sudo apt update
          sudo apt install -y jq unzip gzip wget

      - name: Download country.mmdb
        run: |
          wget -O country.mmdb \
          https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/country-lite.mmdb


      - name: Get latest mihomo version
        id: mihomo
        run: |
          VERSION=$(curl -s https://api.github.com/repos/MetaCubeX/mihomo/releases/latest | jq -r .tag_name)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "mihomo latest version: $VERSION"


      - name: Download mihomo windows
        run: |
          VERSION=${{ steps.mihomo.outputs.version }}

          wget -O mihomo-win.zip \
          https://github.com/MetaCubeX/mihomo/releases/download/${VERSION}/mihomo-windows-amd64-v1-go120-${VERSION}.zip

          unzip -o mihomo-win.zip

          mv mihomo-windows-amd64-v1-go120.exe mihomo.exe

          rm mihomo-win.zip


      - name: Download mihomo macOS
        run: |
          VERSION=${{ steps.mihomo.outputs.version }}

          wget -O mihomo.gz \
          https://github.com/MetaCubeX/mihomo/releases/download/${VERSION}/mihomo-darwin-amd64-v1-go120-${VERSION}.gz

          gzip -d mihomo.gz

          chmod +x mihomo


      - name: Download metacubexd ui
        run: |
          wget -O ui.zip \
          https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip

          unzip ui.zip

          mv metacubexd-gh-pages ui

          rm ui.zip


      - name: Create package
        run: |
          zip -r mihomo.zip . \
          -x ".git/*"


      - name: Delete old release
        continue-on-error: true
        run: |
          gh release delete latest \
          --yes \
          --cleanup-tag

        env:
          GH_TOKEN: ${{ github.token }}


      - name: Create new release
        run: |
          gh release create latest \
          mihomo.zip \
          --title "Mihomo Package Latest" \
          --notes "Auto build $(date)"

        env:
          GH_TOKEN: ${{ github.token }}